#!/usr/bin/env node
const fs = require("fs")
const path = require("path")

// Read NEXT_PUBLIC_CLIENT_ID from environment or .env.local
let clientId = process.env.NEXT_PUBLIC_CLIENT_ID

if (!clientId) {
  const envPath = path.resolve(__dirname, "../.env.local")
  if (fs.existsSync(envPath)) {
    const line = fs.readFileSync(envPath, "utf8")
      .split("\n")
      .find(l => l.startsWith("NEXT_PUBLIC_CLIENT_ID="))
    if (line) clientId = line.split("=")[1].trim()
  }
}

if (!clientId) {
  console.log("No NEXT_PUBLIC_CLIENT_ID set — active-client.ts unchanged.")
  process.exit(0)
}

const clientFile = path.resolve(__dirname, `../config/clients/${clientId}.ts`)
if (!fs.existsSync(clientFile)) {
  console.error(`Client not found: config/clients/${clientId}.ts`)
  process.exit(1)
}

const output = `// Auto-generated by set-client.js — do not edit manually.\nexport { config } from './clients/${clientId}'\n`
fs.writeFileSync(path.resolve(__dirname, "../config/active-client.ts"), output)
console.log(`Active client set to: ${clientId}`)
