import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Beza Boutique",
    tagline: "Women's Fashion & Accessories in Atlanta, GA",
    phone: "+1 (404) 555-0673",
    email: "hello@bezaboutique.com",
    address: "675 Ponce De Leon Ave NE",
    city: "Atlanta",
    state: "GA",
    logo: "https://cdn.zikwala.com/demo/boutique/beza-boutique/logo.png",
    niche: "boutique",
  },
  theme: {
    primary: "#1A1A1A",
    secondary: "#C9A84C",
    accent: "#F9F5F0",
    surface: "#FDFCFA",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "sm",
    darkMode: false,
  },
  tier: "standard",
  isDemo: true,
  seo: {
    title: "Beza Boutique | Women's Fashion & Accessories in Atlanta, GA",
    description:
      "Shop curated women's clothing, shoes, and accessories at Beza Boutique in Atlanta, GA. New arrivals weekly. Order via WhatsApp.",
    keywords: [
      "women's boutique Atlanta GA",
      "fashion boutique Atlanta",
      "women's clothing Atlanta",
      "boutique shop Atlanta GA",
      "accessories boutique Atlanta",
    ],
    ogImage: "https://cdn.zikwala.com/demo/boutique/beza-boutique/hero.jpg",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Shop", href: "/products" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Shop Now",
    ctaHref: "/products",
  },
  hero: {
    heading: "Style That Tells Your Story",
    variant: "magazine",
    subheading:
      "Curated women's fashion, shoes, and accessories. New arrivals every week. Order instantly on WhatsApp.",
    cta: { label: "Shop Now", href: "/products" },
    secondaryCta: { label: "Contact Us", href: "/contact" },
    image: "https://cdn.zikwala.com/demo/boutique/hero.jpg",
    badge: "New Arrivals Weekly",
    trustPoints: ["Free Delivery over $150", "Easy WhatsApp Orders", "New Arrivals Weekly"],
    socialProof: { count: "1,500+", label: "happy shoppers in Atlanta & online" },
  },
  services: {
    title: "More Than a Store",
    subtitle: "We go beyond selling clothes",
    items: [
      {
        name: "Personal Styling",
        description:
          "Not sure what to wear? Book a free 30-min styling session and we'll put together outfits tailored to your style and body type.",
        icon: "Sparkles",
      },
      {
        name: "Custom Orders",
        description:
          "Want a specific color, size, or piece? We source and order on request. Just send us a message with what you're looking for.",
        icon: "PackageCheck",
      },
      {
        name: "Gift Bundles",
        description:
          "Curated gift sets for birthdays, baby showers, and special occasions. Beautifully packaged and ready to give.",
        icon: "Gift",
      },
      {
        name: "Alterations & Tailoring",
        description:
          "Need a perfect fit? We work with a trusted local tailor for alterations on any item you purchase from us.",
        icon: "Scissors",
      },
    ],
  },
  gallery: {
    title: "Style Lookbook",
    subtitle: "How our customers are wearing it",
    images: [
      { src: "https://cdn.zikwala.com/demo/boutique/gallery1.jpg", alt: "Summer dress Atlanta" },
      { src: "https://cdn.zikwala.com/demo/boutique/gallery2.jpg", alt: "Accessories collection" },
      { src: "https://cdn.zikwala.com/demo/boutique/gallery3.jpg", alt: "Evening wear boutique" },
      { src: "https://cdn.zikwala.com/demo/boutique/gallery4.jpg", alt: "Casual fashion Atlanta" },
      { src: "https://cdn.zikwala.com/demo/boutique/gallery5.jpg", alt: "Shoes collection" },
      { src: "https://cdn.zikwala.com/demo/boutique/gallery6.jpg", alt: "Handbag collection" },
    ],
  },
  products: {
    title: "Shop the Collection",
    subtitle: "New arrivals weekly — order instantly on WhatsApp",
    items: [
      {
        id: "pr1",
        name: "Floral Wrap Midi Dress",
        description: "Flowy and flattering. Perfect for brunch, events, or a night out.",
        price: 89,
        originalPrice: 130,
        image: "https://cdn.zikwala.com/demo/boutique/product1.jpg",
        category: "Dresses",
        badge: "Sale",
        inStock: true,
      },
      {
        id: "pr2",
        name: "Ribbed Knit Co-ord Set",
        description: "Matching top and wide-leg trousers in a soft ribbed knit. Available in 4 colors.",
        price: 75,
        image: "https://cdn.zikwala.com/demo/boutique/product2.jpg",
        category: "Sets",
        badge: "Best Seller",
        inStock: true,
      },
      {
        id: "pr3",
        name: "Block Heel Mule — Camel",
        description: "Elegant block heel mule in camel leather. Comfortable for all-day wear.",
        price: 95,
        image: "https://cdn.zikwala.com/demo/boutique/product3.jpg",
        category: "Shoes",
        badge: "New",
        inStock: true,
      },
      {
        id: "pr4",
        name: "Structured Tote Bag — Black",
        description: "Classic black structured tote. Fits a 15\" laptop. Gold hardware finish.",
        price: 110,
        originalPrice: 145,
        image: "https://cdn.zikwala.com/demo/boutique/product4.jpg",
        category: "Bags",
        badge: "Sale",
        inStock: true,
      },
      {
        id: "pr5",
        name: "Satin Slip Dress — Champagne",
        description: "Elegant satin slip dress with adjustable straps. Perfect for evenings.",
        price: 65,
        image: "https://cdn.zikwala.com/demo/boutique/product5.jpg",
        category: "Dresses",
        inStock: true,
      },
      {
        id: "pr6",
        name: "Gold Layered Necklace Set",
        description: "Set of 3 dainty gold-plated necklaces in varying lengths. Tarnish-resistant.",
        price: 38,
        image: "https://cdn.zikwala.com/demo/boutique/product6.jpg",
        category: "Accessories",
        badge: "Best Seller",
        inStock: true,
      },
      {
        id: "pr7",
        name: "Linen Blazer — Ivory",
        description: "Relaxed linen blazer. Wear open over a dress or buttoned as a top.",
        price: 85,
        image: "https://cdn.zikwala.com/demo/boutique/product7.jpg",
        category: "Tops",
        badge: "New",
        inStock: true,
      },
      {
        id: "pr8",
        name: "Chunky Platform Sneakers",
        description: "White chunky platform sneakers. Streetwear-inspired, very comfortable sole.",
        price: 78,
        originalPrice: 98,
        image: "https://cdn.zikwala.com/demo/boutique/product8.jpg",
        category: "Shoes",
        inStock: false,
      },
      {
        id: "pr9",
        name: "Silk Hair Scarf — Multi-print",
        description: "100% silk hair scarf in a bold African-inspired print. Versatile styling.",
        price: 28,
        image: "https://cdn.zikwala.com/demo/boutique/product9.jpg",
        category: "Accessories",
        inStock: true,
      },
    ],
  },
  testimonials: {
    title: "Customer Love",
    subtitle: "Atlanta women trust Beza Boutique",
    items: [
      {
        name: "Nadia F.",
        role: "Customer, Decatur GA",
        text: "I ordered the wrap dress on WhatsApp and it arrived next day. Fits perfectly and the quality is amazing. Will be back for more!",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/boutique/beza-boutique/testimonial-1.jpg",
      },
      {
        name: "Liya M.",
        role: "Customer, Atlanta GA",
        text: "Beza Boutique has the best curation in Atlanta. Every piece I've bought has gotten so many compliments. Love the styling help too.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/boutique/beza-boutique/testimonial-2.jpg",
      },
      {
        name: "Jasmine K.",
        role: "Customer, Stone Mountain GA",
        text: "Ordered a gift bundle for my sister's birthday — the packaging was gorgeous and she loved everything. 10/10.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/boutique/beza-boutique/testimonial-3.jpg",
      },
    ],
  },
  stats: {
    items: [
      { label: "Happy Shoppers", value: "1,500+" },
      { label: "New Arrivals", value: "Weekly" },
      { label: "5-Star Reviews", value: "280+" },
      { label: "Brands Curated", value: "15+" },
    ],
  },
  about: {
    title: "About Beza Boutique",
    story:
      "Beza Boutique was founded in Atlanta with one purpose — to make every woman feel beautiful, confident, and seen. We hand-pick every piece in our collection, focusing on quality fabrics, flattering cuts, and styles that celebrate all body types. Whether you're shopping for everyday basics or a special occasion, we want you to love what you wear.",
    image: "https://cdn.zikwala.com/demo/boutique/beza-boutique/owner.jpg",
    highlights: [
      { label: "Founded", value: "2019" },
      { label: "Location", value: "Atlanta, GA" },
      { label: "Delivery", value: "Atlanta & Nationwide" },
      { label: "Returns", value: "7-day exchange" },
    ],
  },
  contact: {
    title: "Get in Touch",
    subtitle: "Questions about sizing, availability, or custom orders? We're here.",
    mapEmbed: "https://maps.google.com/maps?q=675+Ponce+De+Leon+Ave+NE,+Atlanta,+GA&output=embed",
    formEndpoint: "mailto:hello@bezaboutique.com",
  },
  googleReviewUrl: "https://g.page/r/beza-boutique-atlanta/review",
  social: {
    instagram: "https://instagram.com",
    facebook: "https://facebook.com",
  },
}
