import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Bulcha Real Estate",
    tagline: "Keller Williams Realty Portland Elite | OR & WA",
    phone: "+1 (503) 884-3030",
    email: "bulchag@kw.com",
    address: "9200 SE Sunnybrook Blvd #205",
    city: "Clackamas",
    state: "OR 97015",
    logo: "https://cdn.zikwala.com/client/bulcha-real-estate/bulcha_logo.jpg",
    niche: "realestate",
  },
  theme: {
    primary: "#2B5F3E",
    secondary: "#C9A84C",
    accent: "#EFF6F2",
    surface: "#F7FBF8",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "lg",
    darkMode: false,
  },
  tier: "basic",
  isDemo: false,
  seo: {
    title: "Bulcha Real Estate | Keller Williams Portland Elite | OR & WA",
    description:
      "Top 10% on RMLS. Rookie of the Year. Buying or selling in Greater Portland Metro? Expert guidance across Oregon & Washington.",
    keywords: [
      "real estate agent Clackamas OR",
      "Clackamas Oregon realtor",
      "real estate agent Portland OR",
      "Portland Oregon realtor",
      "buy home Portland OR",
      "sell home Portland",
      "Keller Williams Portland",
      "RMLS top agent Portland",
      "homes for sale Portland Oregon",
      "Vancouver WA real estate",
    ],
    ogImage: "https://cdn.zikwala.com/client/bulcha-real-estate/bulcha.jpg",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Free Consultation",
    ctaHref: "/contact",
  },
  hero: {
    heading: "Your Portland Home Journey Starts Here",
    variant: "magazine",
    subheading:
      "Top 10% on RMLS. Rookie of the Year. Trusted real estate expert across Greater Portland Metro, Oregon & Washington.",
    cta: { label: "Free Consultation", href: "/contact" },
    secondaryCta: { label: "View Sold Listings", href: "/sold" },
    image: "https://cdn.zikwala.com/client/bulcha-real-estate/bulcha_hero_2.jpg",
    badge: "🥇 Rookie of the Year",
    trustPoints: ["Top 10% on RMLS", "Licensed in OR & WA", "Keller Williams Portland Elite"],
    socialProof: { count: "Top 10%", label: "on RMLS — Greater Portland Metro" },
  },
  services: {
    title: "Real Estate Services",
    subtitle: "Expert guidance across Oregon & Washington",
    items: [
      {
        name: "Home Buying",
        description:
          "From pre-approval to closing, I guide first-time and experienced buyers through every step of the Portland market.",
        icon: "Home",
      },
      {
        name: "Home Selling",
        description:
          "Strategic pricing, professional staging, and aggressive marketing to get your Portland home sold fast and at top dollar.",
        icon: "TrendingUp",
      },
      {
        name: "Investment Properties",
        description:
          "Find income-producing properties across Portland, Beaverton, Lake Oswego, and Vancouver, WA.",
        icon: "Building2",
      },
      {
        name: "Relocation Services",
        description:
          "Moving to the Portland metro area? I make your transition smooth with deep local knowledge of OR & WA neighborhoods.",
        icon: "MapPin",
      },
    ],
  },
  soldListings: {
    title: "Recent Closings",
    subtitle: "Homes sold across Portland, Lake Oswego & Vancouver WA",
    items: [
      {
        image: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
        address: "1025 NW Couch St #412",
        city: "Portland, OR",
        price: 695000,
        type: "Condo",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1250,
        soldYear: 2024,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property2.jpg",
        address: "3840 Lakeview Blvd",
        city: "Lake Oswego, OR",
        price: 1180000,
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 3100,
        soldYear: 2024,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property3.jpg",
        address: "6720 SW Hall Blvd",
        city: "Beaverton, OR",
        price: 628000,
        type: "House",
        bedrooms: 4,
        bathrooms: 2,
        sqft: 2200,
        soldYear: 2023,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property4.jpg",
        address: "415 SE Belmont St #3B",
        city: "Portland, OR",
        price: 389000,
        type: "Apartment",
        bedrooms: 1,
        bathrooms: 1,
        sqft: 780,
        soldYear: 2023,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property5.jpg",
        address: "9318 NE Highway 99",
        city: "Vancouver, WA",
        price: 502000,
        type: "House",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1600,
        soldYear: 2024,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property6.jpg",
        address: "2845 SW Fairmount Blvd",
        city: "Portland, OR",
        price: 872000,
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2750,
        soldYear: 2024,
      },
    ],
  },
  testimonials: {
    title: "Client Success Stories",
    subtitle: "Trusted by buyers and sellers across Portland Metro",
    items: [
      {
        name: "Chali Hamda",
        role: "Home Buyer, Portland Metro",
        text: "Bulcha always answers his phone and takes the time to respond to all my questions. He never pressures you — he truly makes sure the house is a good fit before moving forward. Very honest and a great person. Highly recommend!",
        rating: 5,
      },
      {
        name: "Asrat Kahissay",
        role: "Home Buyer, Portland Metro",
        text: "Bulcha Real Estate was amazing to work with. Very professional and an excellent negotiator. Bulcha negotiated the price and closing costs in my favor and guided me smoothly through the entire process. Highly recommend!",
        rating: 5,
      },
      {
        name: "Medasso Gemeda",
        role: "Client, Portland Metro",
        text: "Bulcha Real Estate is knowledgeable, customer focused, well organized, answers your questions on time and walks with you through every step and challenge, guiding you in the right direction. If you want to buy or sell property in this area, Bulcha Real Estate is your best choice!",
        rating: 5,
      },
    ],
  },
  stats: {
    items: [
      { label: "RMLS Ranking", value: "Top 10%" },
      { label: "Google Rating", value: "⭐ 5.0" },
      { label: "Client Satisfaction", value: "100%" },
      { label: "Award", value: "🥇 Rookie of Year" },
    ],
  },
  about: {
    title: "About Bulcha",
    sections: [
      {
        heading: "Meet Wakjira G. Alamu",
        body: "Bulcha is a Keller Williams Realty Portland Elite agent serving the Greater Portland Metro area across Oregon and Washington. Recognized as Rookie of the Year and ranked in the Top 10% on RMLS, Bulcha brings energy, deep market knowledge, and genuine care to every transaction — whether you're buying your first home or selling your forever home.",
        image: "https://cdn.zikwala.com/client/bulcha-real-estate/bulcha_hero_2.jpg",
        highlights: [
          { label: "Licensed in", value: "OR & WA" },
          { label: "Brokerage", value: "KW Portland Elite" },
          { label: "Award", value: "🥇 Rookie of the Year" },
          { label: "RMLS Rank", value: "Top 10%" },
        ],
      },
      {
        heading: "My Commitment to You",
        body: "Real estate is one of the biggest decisions of your life — and I don't take that lightly. From Beaverton to Lake Oswego, from Portland's Pearl District to Vancouver, WA, I bring local expertise and honest guidance to every deal. My goal is simple: get you the best outcome, every time.",
        image: "https://cdn.zikwala.com/client/bulcha-real-estate/bulch_reward2.jpg",
      },
    ],
  },
  contact: {
    title: "Let's Talk Real Estate",
    subtitle: "Schedule your free consultation — Portland, OR & Vancouver, WA.",
    mapEmbed: "https://maps.google.com/maps?q=9200+SE+Sunnybrook+Blvd+%23205,+Clackamas,+OR+97015&output=embed",
    formEndpoint: "mailto:bulchag@kw.com",
  },
  stickyContact: "both",
  googleReviewUrl: "https://maps.app.goo.gl/Yyc5cuDxvEUZ9Pmv9",
  social: {
    facebook: "https://www.facebook.com/share/1Ca5iyQhwV/?mibextid=wwXIfr",
    instagram: "https://www.instagram.com/bulcha_real_estate?igsh=MWNvZDB2NDRrbjVoaA==",
    tiktok: "https://www.tiktok.com/@bulcha_real_estate?_r=1&_t=ZP-95ee54NRboM",
  },
}
