import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Bulcha Real Estate",
    tagline: "Keller Williams Realty Portland Elite | OR & WA",
    phone: "+1 (240) 614-0812",
    email: "bulcha@kwportland.com",
    address: "1220 SW Morrison St",
    city: "Portland",
    state: "OR",
    logo: "https://cdn.zikwala.com/demo/realestate/bulcha-real-estate/bulcha_logo.jpg",
    niche: "realestate",
  },
  theme: {
    primary: "#2B5F3E",
    secondary: "#C9A84C",
    accent: "#EFF6F2",
    surface: "#F7FBF8",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "lg",
    darkMode: false,
  },
  tier: "standard",
  isDemo: true,
  seo: {
    title: "Bulcha Real Estate | Keller Williams Portland Elite | OR & WA",
    description:
      "Top 10% on RMLS. Rookie of the Year. Buying or selling in Greater Portland Metro? Expert guidance across Oregon & Washington.",
    keywords: [
      "real estate agent Portland OR",
      "Portland Oregon realtor",
      "buy home Portland OR",
      "sell home Portland",
      "Keller Williams Portland",
      "RMLS top agent Portland",
      "homes for sale Portland Oregon",
      "Vancouver WA real estate",
    ],
    ogImage: "https://cdn.zikwala.com/demo/realestate/bulcha-real-estate/bulcha.jpg",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Properties", href: "/properties" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Free Consultation",
    ctaHref: "/contact",
  },
  hero: {
    heading: "Your Portland Home Journey Starts Here",
    variant: "magazine",
    subheading:
      "Top 10% on RMLS. Rookie of the Year. Trusted real estate expert across Greater Portland Metro, Oregon & Washington.",
    cta: { label: "Free Consultation", href: "/contact" },
    secondaryCta: { label: "View Listings", href: "/properties" },
    image: "https://cdn.zikwala.com/demo/realestate/hero.jpg",
    badge: "🥇 Rookie of the Year",
    trustPoints: ["Top 10% on RMLS", "Licensed in OR & WA", "Keller Williams Portland Elite"],
    socialProof: { count: "Top 10%", label: "on RMLS — Greater Portland Metro" },
  },
  services: {
    title: "Real Estate Services",
    subtitle: "Expert guidance across Oregon & Washington",
    items: [
      {
        name: "Home Buying",
        description:
          "From pre-approval to closing, I guide first-time and experienced buyers through every step of the Portland market.",
        icon: "Home",
      },
      {
        name: "Home Selling",
        description:
          "Strategic pricing, professional staging, and aggressive marketing to get your Portland home sold fast and at top dollar.",
        icon: "TrendingUp",
      },
      {
        name: "Investment Properties",
        description:
          "Find income-producing properties across Portland, Beaverton, Lake Oswego, and Vancouver, WA.",
        icon: "Building2",
      },
      {
        name: "Relocation Services",
        description:
          "Moving to the Portland metro area? I make your transition smooth with deep local knowledge of OR & WA neighborhoods.",
        icon: "MapPin",
      },
    ],
  },
  gallery: {
    title: "Featured Listings",
    subtitle: "Properties across Portland, Lake Oswego & Vancouver WA",
    images: [
      { src: "https://cdn.zikwala.com/demo/realestate/property1.jpg", alt: "Pearl District condo Portland",     badge: "For Sale" },
      { src: "https://cdn.zikwala.com/demo/realestate/property2.jpg", alt: "Lake Oswego luxury home",           badge: "For Sale" },
      { src: "https://cdn.zikwala.com/demo/realestate/property3.jpg", alt: "Beaverton family home",             badge: "For Sale" },
      { src: "https://cdn.zikwala.com/demo/realestate/property4.jpg", alt: "SE Portland apartment",             badge: "For Rent" },
      { src: "https://cdn.zikwala.com/demo/realestate/property5.jpg", alt: "Vancouver WA investment property",  badge: "Under Contract" },
      { src: "https://cdn.zikwala.com/demo/realestate/property6.jpg", alt: "West Hills Portland home",          badge: "Sold" },
    ],
  },
  properties: {
    title: "Active Listings",
    subtitle: "Homes for sale and rent across Greater Portland Metro",
    items: [
      {
        id: "p1",
        title: "Modern Loft in the Pearl District",
        address: "1025 NW Couch St, #412",
        city: "Portland, OR",
        price: 699000,
        status: "For Sale",
        type: "Condo",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1250,
        image: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
        badge: "New Listing",
      },
      {
        id: "p2",
        title: "Luxury Home in Lake Oswego",
        address: "3840 Lakeview Blvd",
        city: "Lake Oswego, OR",
        price: 1175000,
        status: "For Sale",
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 3100,
        image: "https://cdn.zikwala.com/demo/realestate/property2.jpg",
        badge: "Price Reduced",
      },
      {
        id: "p3",
        title: "Family Home in Beaverton",
        address: "6720 SW Hall Blvd",
        city: "Beaverton, OR",
        price: 625000,
        status: "For Sale",
        type: "House",
        bedrooms: 4,
        bathrooms: 2,
        sqft: 2200,
        image: "https://cdn.zikwala.com/demo/realestate/property3.jpg",
        badge: "Open House",
      },
      {
        id: "p4",
        title: "Stylish Apartment in SE Portland",
        address: "415 SE Belmont St, #3B",
        city: "Portland, OR",
        price: 2200,
        status: "For Rent",
        type: "Apartment",
        bedrooms: 1,
        bathrooms: 1,
        sqft: 780,
        image: "https://cdn.zikwala.com/demo/realestate/property4.jpg",
        badge: "Just Listed",
      },
      {
        id: "p5",
        title: "Investment Property in Vancouver",
        address: "9318 NE Highway 99",
        city: "Vancouver, WA",
        price: 499000,
        status: "Under Contract",
        type: "House",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1600,
        image: "https://cdn.zikwala.com/demo/realestate/property5.jpg",
      },
      {
        id: "p6",
        title: "Contemporary Home in West Hills",
        address: "2845 SW Fairmount Blvd",
        city: "Portland, OR",
        price: 875000,
        status: "Sold",
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2750,
        image: "https://cdn.zikwala.com/demo/realestate/property6.jpg",
      },
    ],
  },
  testimonials: {
    title: "Client Success Stories",
    subtitle: "Trusted by buyers and sellers across Portland Metro",
    items: [
      {
        name: "Rachel M.",
        role: "First-time Buyer, Beaverton OR",
        text: "Bulcha made the whole process so easy. As a first-time buyer I was nervous, but he explained everything clearly and got me a great deal.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/bulcha-real-estate/testimonial-1.jpg",
      },
      {
        name: "Kevin & Sara T.",
        role: "Sellers, Lake Oswego OR",
        text: "Listed on Thursday, had multiple offers by Sunday, and sold above asking. Bulcha's marketing strategy was outstanding.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/bulcha-real-estate/testimonial-2.jpg",
      },
      {
        name: "Amir H.",
        role: "Investor, Vancouver WA",
        text: "Helped me find a great investment property across the border in Vancouver. Knows both the OR and WA markets extremely well.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/bulcha-real-estate/testimonial-3.jpg",
      },
    ],
  },
  stats: {
    items: [
      { label: "RMLS Ranking", value: "Top 10%" },
      { label: "Homes Sold", value: "80+" },
      { label: "Client Satisfaction", value: "98%" },
      { label: "Avg Days on Market", value: "11" },
    ],
  },
  about: {
    title: "About Bulcha",
    story:
      "Bulcha is a Keller Williams Realty Portland Elite agent serving the Greater Portland Metro area across Oregon and Washington. Recognized as Rookie of the Year and ranked in the Top 10% on RMLS, Bulcha brings energy, market knowledge, and genuine care to every transaction. Whether you're buying your first home in Beaverton, selling in Lake Oswego, or investing across the border in Vancouver, WA — Bulcha is your local expert.",
    image: "https://cdn.zikwala.com/demo/realestate/bulcha-real-estate/bulcha.jpg",
    highlights: [
      { label: "Licensed in", value: "OR & WA" },
      { label: "Brokerage", value: "KW Portland Elite" },
      { label: "Award", value: "🥇 Rookie of the Year" },
      { label: "RMLS Rank", value: "Top 10%" },
    ],
  },
  contact: {
    title: "Let's Talk Real Estate",
    subtitle: "Schedule your free consultation — Portland, OR & Vancouver, WA.",
    mapEmbed: "https://maps.google.com/maps?q=1220+SW+Morrison+St,+Portland,+OR&output=embed",
    formEndpoint: "mailto:bulcha@kwportland.com",
  },
  googleReviewUrl: "https://g.page/r/bulcha-real-estate-portland/review",
  social: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
  },
}
