import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Daniel Hailu – Real Estate Agent",
    tagline: "Your Trusted Real Estate Partner in the DMV Area",
    phone: "+1 (202) 500-5095",
    email: "danielhailu2721@gmail.com",
    address: "8701 Georgia Ave",
    city: "Silver Spring",
    state: "MD",
    logo: "https://cdn.zikwala.com/demo/realestate/daniel-hailu/daniel-hailu-logo.jpg",
    niche: "realestate",
  },
  theme: {
    primary: "#1A3C5E",
    secondary: "#C9A84C",
    accent: "#FBF5E6",
    surface: "#FDFAF5",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "lg",
    darkMode: false,
  },
  tier: "basic",
  isDemo: true,
  isActive: true,
  seo: {
    title: "Daniel Hailu | Real Estate Agent in the DMV Area",
    description:
      "Buy, sell, or rent property across Maryland, Washington, D.C., and Virginia with a trusted local agent. 12+ years of experience and 300+ successful transactions.",
    keywords: [
      "real estate agent Maryland",
      "DMV realtor",
      "Maryland real estate agent",
      "buy home Maryland",
      "sell home Maryland",
      "Ethiopian realtor DMV",
      "homes for sale Maryland",
      "homes for sale Washington DC",
      "homes for sale Virginia",
    ],
    ogImage: "https://cdn.zikwala.com/demo/realestate/daniel-hailu/daniel-hailu1.jpg",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Calculator", href: "/mortgage-calculator" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Free Consultation",
    ctaHref: "/contact",
  },
  hero: {
    heading: "Your DMV Home Journey Starts Here",
    variant: "bold",
    subheading:
      "Trusted real estate expert serving Maryland, Washington D.C., and Virginia. Fluent in English & Amharic.",
    cta: { label: "Free Consultation", href: "/contact" },
    secondaryCta: { label: "View Listings", href: "/properties" },
    image: "https://cdn.zikwala.com/demo/realestate/hero.jpg",
    badge: "Licensed in MD · English & Amharic",
    trustPoints: ["12+ Years in the DMV", "300+ Transactions Closed", "Free Consultation"],
    socialProof: { count: "300+", label: "homes sold across the DMV area" },
  },
  services: {
    title: "Real Estate Services",
    subtitle: "Expert guidance at every step of your journey",
    items: [
      {
        name: "Home Buying",
        description:
          "From pre-approval to closing, we guide first-time and experienced buyers through every step.",
        icon: "Home",
      },
      {
        name: "Home Selling",
        description:
          "Strategic pricing, professional staging, and marketing to sell your home fast and at top dollar.",
        icon: "TrendingUp",
      },
      {
        name: "Rental & Investment",
        description:
          "Find income-producing properties or quality rentals in prime DMV locations.",
        icon: "Building2",
      },
      {
        name: "Relocation Services",
        description:
          "Moving to the DMV area? We make your transition seamless with local expertise.",
        icon: "MapPin",
      },
    ],
  },
  soldListings: {
    title: "Recently Sold",
    subtitle: "A track record of results across the DMV — homes sold fast and above asking",
    items: [
      {
        image: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
        address: "412 Sligo Ave",
        city: "Silver Spring, MD",
        price: 635000,
        type: "Townhouse",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1850,
        soldYear: 2024,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property2.jpg",
        address: "1425 Rhode Island Ave NW",
        city: "Washington, D.C.",
        price: 748000,
        type: "Condo",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1100,
        soldYear: 2024,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property3.jpg",
        address: "3900 University Dr",
        city: "Fairfax, VA",
        price: 875000,
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2400,
        soldYear: 2023,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property4.jpg",
        address: "7800 Old Georgetown Rd",
        city: "Bethesda, MD",
        price: 820000,
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2800,
        soldYear: 2023,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property5.jpg",
        address: "6500 Belcrest Rd",
        city: "Hyattsville, MD",
        price: 580000,
        type: "House",
        bedrooms: 3,
        bathrooms: 1,
        sqft: 1400,
        soldYear: 2024,
      },
      {
        image: "https://cdn.zikwala.com/demo/realestate/property6.jpg",
        address: "3605 N Glebe Rd",
        city: "Arlington, VA",
        price: 695000,
        type: "Condo",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1050,
        soldYear: 2024,
      },
    ],
  },
  testimonials: {
    title: "Client Success Stories",
    subtitle: "Trusted by families across the DMV area",
    items: [
      {
        name: "Mekdes A.",
        role: "First-time Buyer, Silver Spring MD",
        text: "Daniel made buying my first home stress-free. Explained everything clearly and negotiated a great deal.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/daniel-hailu/testimonial-1.jpg",
      },
      {
        name: "Daniel G.",
        role: "Seller, Washington D.C.",
        text: "Sold my home quickly and above asking price. Excellent marketing and communication.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/daniel-hailu/testimonial-2.jpg",
      },
      {
        name: "Tigist B.",
        role: "Investor, Fairfax VA",
        text: "Found a great investment property with strong ROI. Daniel knows the DMV market extremely well.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/daniel-hailu/testimonial-3.jpg",
      },
    ],
  },
  stats: {
    items: [
      { label: "Homes Sold", value: "300+" },
      { label: "Years Experience", value: "12+" },
      { label: "Client Satisfaction", value: "98%" },
      { label: "Avg Days on Market", value: "14" },
    ],
  },
  about: {
    title: "About Daniel Hailu",
    story:
      "With over 12 years of experience in the DMV real estate market, Daniel brings deep local knowledge and a personal touch to every transaction. As part of the Ethiopian community in Maryland, he understands the unique needs of families and investors looking to plant roots in the area.",
    image: "https://cdn.zikwala.com/demo/realestate/daniel-hailu/daniel-hailu1.jpg",
    highlights: [
      { label: "Licensed in", value: "MD" },
      { label: "Transactions Closed", value: "300+" },
      { label: "Languages", value: "English, Amharic" },
      { label: "Specialization", value: "Residential & Investment" },
    ],
  },
  mortgageCalculator: true,
  homeValuation: true,
  howItWorks: true,

  areasServed: [
    { name: "Silver Spring, MD", description: "Home base — deep knowledge of neighborhoods, schools, and market trends." },
    { name: "Bethesda, MD", description: "Luxury homes, condos, and investment properties in one of MD's top markets." },
    { name: "Rockville, MD", description: "Family-friendly communities with strong resale value and great schools." },
    { name: "Washington, D.C.", description: "Condos, row houses, and multi-unit investments in all major DC neighborhoods." },
    { name: "Arlington, VA", description: "High-demand properties close to Metro lines and Amazon HQ2." },
    { name: "Fairfax, VA", description: "Spacious single-family homes and townhouses for growing families." },
  ],

  faq: [
    { question: "How do I start the home buying process?", answer: "The first step is a free consultation where we discuss your goals, budget, and timeline. We'll connect you with a trusted lender for pre-approval so you can shop with confidence." },
    { question: "How long does it take to buy a home in the DMV?", answer: "Typically 30–60 days from offer to closing, though it depends on financing, inspection, and market conditions. We'll keep you informed at every step." },
    { question: "What does it cost to work with you as a buyer?", answer: "Nothing — as a buyer, our services are free to you. The seller pays the agent commissions. You get full representation at no cost." },
    { question: "How do you determine the right listing price for my home?", answer: "We run a detailed Comparative Market Analysis (CMA) looking at recent sales, active listings, and market trends in your neighborhood to price your home competitively." },
    { question: "Do you work with first-time homebuyers?", answer: "Absolutely. We specialize in guiding first-time buyers through the entire process — from understanding financing to closing day — in English and Amharic." },
    { question: "What areas do you cover?", answer: "We serve the entire DMV — Maryland (Silver Spring, Bethesda, Rockville, Hyattsville), Washington D.C., and Northern Virginia (Arlington, Fairfax, Alexandria)." },
  ],

  contact: {
    title: "Let's Talk Real Estate",
    subtitle: "Schedule your free consultation today — available in English and Amharic.",
    mapEmbed: "https://maps.google.com/maps?q=8701+Georgia+Ave,+Silver+Spring,+MD&output=embed",
    formEndpoint: "mailto:danielhailu2721@gmail.com",
  },
  googleReviewUrl: "https://g.page/r/daniel-hailu-realestate/review",
  social: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
  },
}
