import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Debela Mengesha - Real Estate Agent",
    tagline: "Your Trusted Real Estate Partner in Phoenix, AZ",
    phone: "+1 (480) 322-0801",
    email: "debela@westusa.com",
    address: "2375 E Camelback Rd",
    city: "Phoenix",
    state: "AZ",
    logo: "https://cdn.zikwala.com/demo/realestate/debela-mengesha/dm_logo.png",
    niche: "realestate",
  },
  theme: {
    primary: "#1A3C5E",
    secondary: "#C9A84C",
    accent: "#FBF5E6",
    surface: "#FDFAF5",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "lg",
    darkMode: false,
  },
  tier: "standard",
  isDemo: true,
  isActive: false,
  seo: {
    title: "Debela Mengesha | Real Estate Agent in Phoenix, AZ",
    description:
      "Buy, sell, or rent property in Phoenix, AZ with a trusted local agent. 12+ years experience, 300+ homes sold.",
    keywords: [
      "real estate agent Phoenix AZ",
      "Phoenix AZ realtor",
      "buy home Phoenix",
      "sell home Scottsdale",
      "Ethiopian realtor Phoenix",
      "homes for sale Phoenix AZ",
    ],
    ogImage: "https://cdn.zikwala.com/demo/realestate/debela-mengesha/dm.jpg",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Free Consultation",
    ctaHref: "/contact",
  },
  hero: {
    heading: "Find Your Dream Home in Phoenix AZ",
    variant: "magazine",

    subheading:
      "Expert real estate guidance for buyers, sellers, and investors in Phoenix AZ.",
    cta: { label: "Free Consultation", href: "/contact" },
    secondaryCta: { label: "View Listings", href: "/gallery" },
    image: "https://cdn.zikwala.com/demo/realestate/hero.jpg",
    badge: "Licensed in AZ",
    trustPoints: ["Licensed in AZ", "Free Consultation", "12+ Years Experience"],
    socialProof: { count: "300+", label: "homes sold across Phoenix AZ" },
  },
  services: {
    title: "Real Estate Services",
    subtitle: "Expert guidance at every step of your journey",
    items: [
      {
        name: "Home Buying",
        description:
          "From pre-approval to closing, we guide first-time and experienced buyers through every step.",
        icon: "Home",
      },
      {
        name: "Home Selling",
        description:
          "Strategic pricing, professional staging, and marketing to sell your home fast and at top dollar.",
        icon: "TrendingUp",
      },
      {
        name: "Rental & Investment",
        description:
          "Find income-producing properties or quality rentals in prime Phoenix AZ locations.",
        icon: "Building2",
      },
      {
        name: "Relocation Services",
        description:
          "Moving to the Phoenix AZ area? We make your transition seamless with local expertise.",
        icon: "MapPin",
      },
    ],
  },
  gallery: {
    title: "Featured Listings",
    subtitle: "Properties we've helped buy, sell, and rent across the Valley",
    images: [
      { src: "https://cdn.zikwala.com/demo/realestate/property1.jpg", alt: "Modern townhouse Phoenix",        badge: "For Sale" },
      { src: "https://cdn.zikwala.com/demo/realestate/property2.jpg", alt: "Scottsdale condo",               badge: "For Sale" },
      { src: "https://cdn.zikwala.com/demo/realestate/property3.jpg", alt: "Gilbert family home",            badge: "For Sale" },
      { src: "https://cdn.zikwala.com/demo/realestate/property4.jpg", alt: "Tempe luxury apartment",         badge: "For Rent" },
      { src: "https://cdn.zikwala.com/demo/realestate/property5.jpg", alt: "Chandler investment property",   badge: "Under Contract" },
      { src: "https://cdn.zikwala.com/demo/realestate/property6.jpg", alt: "North Scottsdale home",          badge: "Sold" },
    ],
  },
  properties: {
    title: "Active Listings",
    subtitle: "Homes for sale and rent across Phoenix, Scottsdale & Tempe",
    items: [
      {
        id: "p1",
        title: "Modern Townhouse in Arcadia",
        address: "4820 E Camelback Rd",
        city: "Phoenix, AZ",
        price: 949000,
        status: "For Sale",
        type: "Townhouse",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1850,
        image: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
        badge: "New Listing",
      },
      {
        id: "p2",
        title: "Stylish Condo in Old Town Scottsdale",
        address: "7135 E Camelback Rd, #302",
        city: "Scottsdale, AZ",
        price: 725000,
        status: "For Sale",
        type: "Condo",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1100,
        image: "https://cdn.zikwala.com/demo/realestate/property2.jpg",
        badge: "Price Reduced",
      },
      {
        id: "p3",
        title: "Single Family Home in Gilbert",
        address: "1845 S Higley Rd",
        city: "Gilbert, AZ",
        price: 889000,
        status: "For Sale",
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2400,
        image: "https://cdn.zikwala.com/demo/realestate/property3.jpg",
        badge: "Open House",
      },
      {
        id: "p4",
        title: "Luxury Apartment in Tempe Town Lake",
        address: "1 E Río Salado Pkwy, #8A",
        city: "Tempe, AZ",
        price: 2800,
        status: "For Rent",
        type: "Apartment",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1050,
        image: "https://cdn.zikwala.com/demo/realestate/property4.jpg",
        badge: "Just Listed",
      },
      {
        id: "p5",
        title: "Investment Property in Chandler",
        address: "2250 W Pecos Rd",
        city: "Chandler, AZ",
        price: 599000,
        status: "Under Contract",
        type: "House",
        bedrooms: 3,
        bathrooms: 1,
        sqft: 1400,
        image: "https://cdn.zikwala.com/demo/realestate/property5.jpg",
      },
      {
        id: "p6",
        title: "Contemporary Home in North Scottsdale",
        address: "9823 E Bell Rd",
        city: "Scottsdale, AZ",
        price: 825000,
        status: "Sold",
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2800,
        image: "https://cdn.zikwala.com/demo/realestate/property6.jpg",
      },
    ],
  },
  testimonials: {
    title: "Client Success Stories",
    subtitle: "Trusted by families across Phoenix & the Valley",
    items: [
      {
        name: "Mekdes A.",
        role: "First-time Buyer, Gilbert AZ",
        text: "Debela made buying my first home stress-free. Explained everything in detail and got me a great deal.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/debela-mengesha/testimonial-1.jpg",
      },
      {
        name: "Daniel G.",
        role: "Seller, Scottsdale AZ",
        text: "Sold my home in 12 days above asking price. Exceptional marketing and negotiation.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/debela-mengesha/testimonial-2.jpg",
      },
      {
        name: "Tigist B.",
        role: "Investor, Phoenix AZ",
        text: "Found me a great rental property with strong ROI. Knows the Phoenix market inside out.",
        rating: 5,
        avatar: "https://cdn.zikwala.com/demo/realestate/debela-mengesha/testimonial-3.jpg",
      },
    ],
  },
  stats: {
    items: [
      { label: "Homes Sold", value: "100+" },
      { label: "Years Experience", value: "10+" },
      { label: "Client Satisfaction", value: "98%" },
      { label: "Avg Days on Market", value: "14" },
    ],
  },
  about: {
    title: "About Debela Mengesha",
    story:
      "With over 12 years of experience in the Phoenix, AZ market, Debela brings deep local knowledge and a personal touch to every transaction. As part of the Ethiopian community in the Valley, he understands the unique needs of families and investors looking to plant roots in Arizona.",
    image: "https://cdn.zikwala.com/demo/realestate/debela-mengesha/dm.jpg",
    highlights: [
      { label: "Licensed in", value: "AZ" },
      { label: "Transactions Closed", value: "100+" },
      { label: "Languages", value: "English, Amharic" },
      { label: "Specialization", value: "Residential & Investment" },
    ],
  },
  contact: {
    title: "Let's Talk Real Estate",
    subtitle: "Schedule your free consultation today.",
    mapEmbed: "https://maps.google.com/maps?q=2375+E+Camelback+Rd,+Phoenix,+AZ&output=embed",
    formEndpoint: "mailto:debela@westusa.com",
  },
  googleReviewUrl: "https://g.page/r/debela-mengesha-realestate/review",

  social: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
  },
}
