import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Habesha Motors",
    tagline: "Quality Pre-Owned Vehicles in the DMV",
    phone: "+1 (703) 555-0330",
    email: "sales@habeshamotors.com",
    address: "2200 Richmond Hwy",
    city: "Arlington",
    state: "VA",
    logo: "/clients/demo-cardealership/logo.png",
    niche: "cardealership",
  },
  theme: {
    primary: "#B91C1C",
    secondary: "#991B1B",
    accent: "#FEE2E2",
    surface: "#FFF5F5",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "md",
    darkMode: false,
  },
  tier: "standard",
  isDemo: true,
  seo: {
    title: "Habesha Motors | Quality Used Cars in Arlington, VA",
    description:
      "Browse quality pre-owned vehicles in Arlington, VA. Cars, SUVs, and trucks — all inspected and ready to drive.",
    keywords: [
      "used cars Arlington VA",
      "pre-owned vehicles DMV",
      "car dealership Virginia",
      "buy used car DC area",
      "Ethiopian car dealer Virginia",
    ],
    ogImage: "/clients/demo-cardealership/og.png",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "View Inventory",
    ctaHref: "/vehicles",
  },
  hero: {
    variant: "bold",
    heading: "Find Your Next Vehicle Today",
    subheading:
      "Quality pre-owned cars, SUVs, and trucks — inspected, priced fairly, and ready to drive in the DMV.",
    cta: { label: "Browse Inventory", href: "#vehicles" },
    secondaryCta: { label: "Call Us", href: "tel:+17035550330" },
    image: "/clients/demo-cardealership/hero.jpg",
    badge: "Financing Available",
    trustPoints: ["All Vehicles Inspected", "Financing Available", "Trade-Ins Welcome"],
    socialProof: { count: "400+", label: "vehicles sold across the DMV" },
  },
  services: {
    title: "Our Services",
    subtitle: "More than just a car lot",
    items: [
      {
        name: "Vehicle Sales",
        description:
          "Wide selection of pre-owned cars, SUVs, trucks, and vans. Every vehicle is inspected before sale.",
        icon: "Car",
      },
      {
        name: "Financing",
        description:
          "We work with multiple lenders to get you the best rate — even with challenged credit.",
        icon: "CreditCard",
      },
      {
        name: "Trade-Ins",
        description:
          "Bring your current vehicle and get a fair trade-in offer applied toward your next purchase.",
        icon: "ArrowLeftRight",
      },
      {
        name: "Vehicle Sourcing",
        description:
          "Can't find what you need? Tell us your specs and budget — we'll find it for you.",
        icon: "Search",
      },
    ],
  },
  vehicles: {
    title: "Current Inventory",
    subtitle: "All vehicles inspected and ready to drive. Prices negotiable.",
    items: [
      {
        id: "v1",
        make: "Toyota",
        model: "Camry",
        year: 2021,
        price: 22500,
        mileage: 31000,
        fuel: "Gasoline",
        transmission: "Automatic",
        color: "Silver",
        image: "/clients/demo-cardealership/vehicles/camry.jpg",
        badge: "Certified",
      },
      {
        id: "v2",
        make: "Honda",
        model: "CR-V",
        year: 2020,
        price: 26900,
        mileage: 44000,
        fuel: "Gasoline",
        transmission: "Automatic",
        color: "White",
        image: "/clients/demo-cardealership/vehicles/crv.jpg",
        badge: "Hot Deal",
      },
      {
        id: "v3",
        make: "Tesla",
        model: "Model 3",
        year: 2022,
        price: 34000,
        mileage: 18000,
        fuel: "Electric",
        transmission: "Automatic",
        color: "Black",
        image: "/clients/demo-cardealership/vehicles/model3.jpg",
        badge: "New Arrival",
      },
      {
        id: "v4",
        make: "Ford",
        model: "F-150",
        year: 2019,
        price: 31500,
        mileage: 62000,
        fuel: "Gasoline",
        transmission: "Automatic",
        color: "Blue",
        image: "/clients/demo-cardealership/vehicles/f150.jpg",
      },
      {
        id: "v5",
        make: "Toyota",
        model: "RAV4 Hybrid",
        year: 2021,
        price: 29800,
        mileage: 27000,
        fuel: "Hybrid",
        transmission: "Automatic",
        color: "Gray",
        image: "/clients/demo-cardealership/vehicles/rav4.jpg",
        badge: "Price Drop",
      },
      {
        id: "v6",
        make: "BMW",
        model: "3 Series",
        year: 2020,
        price: 32000,
        mileage: 38000,
        fuel: "Gasoline",
        transmission: "Automatic",
        color: "White",
        image: "/clients/demo-cardealership/vehicles/bmw3.jpg",
        sold: true,
      },
    ],
  },
  testimonials: {
    title: "What Our Customers Say",
    subtitle: "Trusted by hundreds of families in the DMV",
    items: [
      {
        name: "Yonas T.",
        role: "Buyer, Alexandria VA",
        text: "Got a great deal on a Honda CR-V. The process was smooth, no pressure, and the car was exactly as described. Highly recommend!",
        rating: 5,
      },
      {
        name: "Meron H.",
        role: "Buyer, Rockville MD",
        text: "They helped me get financing even when other dealers turned me away. Drove home in a Toyota Camry the same day.",
        rating: 5,
      },
      {
        name: "Samuel A.",
        role: "Buyer, DC",
        text: "Traded in my old car and got a fair value. No games, straightforward pricing. Will be back for my next car.",
        rating: 5,
      },
    ],
  },
  stats: {
    items: [
      { label: "Vehicles Sold", value: "400+" },
      { label: "Years in Business", value: "8+" },
      { label: "5-Star Reviews", value: "200+" },
      { label: "Financing Options", value: "10+" },
    ],
  },
  about: {
    title: "About Habesha Motors",
    story:
      "Habesha Motors has been serving the DMV community for over 8 years. We specialize in quality pre-owned vehicles at fair prices, with financing options for every budget. As a community-owned business, we believe in honest deals and long-term relationships.",
    image: "/clients/demo-cardealership/about.jpg",
    highlights: [
      { label: "Founded", value: "2016" },
      { label: "Location", value: "Arlington, VA" },
      { label: "Inventory", value: "30–50 vehicles" },
      { label: "Languages", value: "English, Amharic" },
    ],
  },
  contact: {
    title: "Get In Touch",
    subtitle: "Have a question about a vehicle? Ready to schedule a test drive? We're here.",
    formEndpoint: "mailto:sales@habeshamotors.com",
  },
  social: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
  },
}
