import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Lumière Jewelry",
    tagline: "Handcrafted Fine Jewelry & Accessories",
    phone: "+1 (555) 000-0000",
    email: "demo@lumierejewelry.com",
    address: "1400 Eye St NW",
    city: "Washington",
    state: "DC",
    logo: "https://cdn.zikwala.com/demo/jewelry/lumiere-logo.png",
    niche: "boutique",
  },
  theme: {
    primary: "#3D1654",
    secondary: "#2A0E3D",
    accent: "#F5EEFF",
    surface: "#FDF9FF",
    onPrimary: "#FFFFFF",
    font: "Cormorant Garamond",
    roundedLevel: "lg",
    darkMode: false,
  },
  tier: "pro",
  isDemo: false,
  isLive: false,
  features: {
    payment: true,
  },
  seo: {
    title: "Lumière Jewelry | Handcrafted Fine Jewelry in Washington DC",
    description:
      "✨ Handcrafted necklaces, earrings, bracelets & rings — starting at $28. Secure checkout. Ships to DC, MD & VA in 1–2 days. Gift-ready packaging included.",
    keywords: [
      "jewelry shop Washington DC",
      "handcrafted jewelry DMV",
      "fine jewelry DC",
      "necklace bracelet earrings DC",
      "jewelry store Maryland Virginia",
      "handmade jewelry gifts",
    ],
    ogImage: "https://cdn.zikwala.com/product/feaf0996-3de5-4731-9394-e0cb5f4c39b8.webp",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Shop", href: "/products" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Shop Now",
    ctaHref: "/products",
  },
  hero: {
    variant: "shop",
    heading: "Jewelry That Tells Your Story",
    subheading:
      "Discover handcrafted necklaces, bracelets, earrings, and rings — curated for every occasion. Add to cart and checkout online with fast delivery across DC, MD & VA.",
    cta: { label: "Shop Jewelry", href: "/products" },
    secondaryCta: { label: "View Cart", href: "/checkout" },
    image: "https://cdn.zikwala.com/demo/decoration/habeshanate/h_hero.jpg",
    imagePosition: "center center",
    badge: "Handcrafted Jewelry · DC, MD & VA",
    trustPoints: ["Handcrafted Quality", "Secure Checkout", "Fast Delivery", "Gift Ready"],
    socialProof: { count: "800+", label: "happy customers across the DMV" },
  },
  products: {
    title: "Our Jewelry Collection",
    subtitle: "Handpicked pieces for every style and occasion",
    items: [
      {
        id: "p1",
        name: "Gold Chain Necklace",
        description: "18k gold-plated layered chain — timeless elegance for any outfit.",
        price: 48,
        originalPrice: 65,
        badge: "Best Seller",
        category: "Necklaces",
        image: "https://cdn.zikwala.com/product/feaf0996-3de5-4731-9394-e0cb5f4c39b8.webp",
        inStock: true,
      },
      {
        id: "p2",
        name: "Crystal Drop Earrings",
        description: "Lightweight crystal drop earrings that catch every light beautifully.",
        price: 32,
        category: "Earrings",
        badge: "New",
        image: "https://cdn.zikwala.com/product/5f4c6bb0-d710-4f32-94a3-53f53560abb0.webp",
        inStock: true,
      },
      {
        id: "p3",
        name: "Beaded Stretch Bracelet",
        description: "Natural stone beads in an adjustable stretch band — great layered or solo.",
        price: 28,
        category: "Bracelets",
        image: "https://cdn.zikwala.com/product/4f74dbc5-7bfb-4218-a75f-fe2ef3f7d87f.webp",
        inStock: true,
      },
      {
        id: "p4",
        name: "Statement Pendant Set",
        description: "Bold pendant necklace + matching earrings — arrives in a gift-ready box.",
        price: 72,
        originalPrice: 95,
        badge: "Gift Set",
        category: "Sets",
        image: "https://cdn.zikwala.com/product/705ca5f6-efc7-460f-9190-2526b55f4cc2.webp",
        inStock: true,
      },
      {
        id: "p5",
        name: "Minimalist Ring Set",
        description: "Stackable rings in gold, rose gold, and silver — mix and match effortlessly.",
        price: 38,
        category: "Rings",
        image: "https://cdn.zikwala.com/product/e8bbaf2d-a6ee-4155-b568-3b178c801c08.webp",
        inStock: true,
      },
      {
        id: "p6",
        name: "Pearl Choker Necklace",
        description: "Freshwater pearl choker with gold clasp — elegant, classic, effortless.",
        price: 55,
        category: "Necklaces",
        badge: "Low Stock",
        image: "https://cdn.zikwala.com/product/a18a3c2a-c91b-4ba4-b4fa-4d080474b555.webp",
        inStock: true,
      },
    ],
  },
  services: {
    title: "Why Shop Lumière",
    subtitle: "Everything you need for a seamless jewelry shopping experience",
    items: [
      {
        name: "Handcrafted Quality",
        description: "Every piece is sourced from skilled artisans — no mass-produced items, ever.",
        icon: "Gem",
      },
      {
        name: "Secure Online Checkout",
        description: "Shop with confidence — SSL-encrypted checkout powered by Stripe.",
        icon: "ShieldCheck",
      },
      {
        name: "Fast Delivery",
        description: "Orders ship within 1–2 business days across DC, Maryland, and Virginia.",
        icon: "Truck",
      },
      {
        name: "Gift-Ready Packaging",
        description: "Every order arrives in a branded box — perfect for birthdays, anniversaries, and holidays.",
        icon: "Gift",
      },
    ],
  },
  gallery: {
    title: "Our Jewelry Collection",
    subtitle: "A glimpse of our handcrafted pieces — every item ships in a gift-ready box",
    images: [
      { src: "https://cdn.zikwala.com/product/feaf0996-3de5-4731-9394-e0cb5f4c39b8.webp", alt: "Necklaces — Gold Chain Necklace" },
      { src: "https://cdn.zikwala.com/product/a18a3c2a-c91b-4ba4-b4fa-4d080474b555.webp", alt: "Necklaces — Pearl Choker" },
      { src: "https://cdn.zikwala.com/product/5f4c6bb0-d710-4f32-94a3-53f53560abb0.webp", alt: "Earrings — Crystal Drop" },
      { src: "https://cdn.zikwala.com/product/4f74dbc5-7bfb-4218-a75f-fe2ef3f7d87f.webp", alt: "Bracelets — Beaded Stretch" },
      { src: "https://cdn.zikwala.com/product/e8bbaf2d-a6ee-4155-b568-3b178c801c08.webp", alt: "Rings — Minimalist Ring Set" },
      { src: "https://cdn.zikwala.com/product/705ca5f6-efc7-460f-9190-2526b55f4cc2.webp", alt: "Sets — Statement Pendant Set" },
    ],
  },
  testimonials: {
    title: "What Our Customers Say",
    subtitle: "Loved by jewelry shoppers across DC, Maryland & Virginia",
    items: [
      {
        name: "Jessica T.",
        role: "Jewelry Customer, Washington DC",
        text: "The gold chain necklace is stunning — it arrived so quickly and the quality is amazing. I've already ordered three more pieces as gifts!",
        rating: 5,
      },
      {
        name: "Priya M.",
        role: "Jewelry Customer, Alexandria VA",
        text: "The pearl choker is absolutely gorgeous. Checkout was seamless and I had it in two days. Will definitely shop again!",
        rating: 5,
      },
      {
        name: "Amara B.",
        role: "Jewelry Customer, Hyattsville MD",
        text: "Ordered the pendant set as a birthday gift — it was a huge hit! Arrived in a beautiful gift box. So easy to order online.",
        rating: 5,
      },
    ],
  },
  stats: {
    items: [
      { label: "Pieces Sold", value: "800+" },
      { label: "Years Experience", value: "6+" },
      { label: "5-Star Reviews", value: "180+" },
      { label: "Happy Customers", value: "800+" },
    ],
  },
  about: {
    title: "About Lumière Jewelry",
    story:
      "Lumière Jewelry was founded with one goal: to make beautiful, high-quality jewelry accessible to everyone in the DMV. We curate handcrafted pieces — necklaces, pendants, bracelets, earrings, and rings — sourced from skilled artisans and delivered to your door. Every piece is chosen with care and arrives in a gift-ready box.",
    image: "https://cdn.zikwala.com/demo/event-panner/event_panning_hero.jpg",
    highlights: [
      { label: "Based in", value: "Washington, DC" },
      { label: "Specialty", value: "Handcrafted Jewelry" },
      { label: "Checkout", value: "Secure Online" },
      { label: "Service Area", value: "DC, MD & Virginia" },
    ],
  },
  contact: {
    title: "Get in Touch",
    subtitle: "Have a question about an order or need help choosing a piece? We reply within 24 hours.",
    mapEmbed: "https://maps.google.com/maps?q=Washington,+DC&output=embed",
    formEndpoint: "mailto:demo@lumierejewelry.com",
    notifyEmail: "demo@lumierejewelry.com",
    whatsappMessage: "Hi! I'm interested in your jewelry. Can you help me?",
  },
  faq: [
    { question: "How do I order jewelry?", answer: "Add items to your cart and checkout securely online. You can also message us on WhatsApp for help choosing a piece." },
    { question: "Do you ship outside DC?", answer: "Yes — we ship across DC, Maryland, and Virginia. Contact us for shipping to other states." },
    { question: "Can I order a piece as a gift?", answer: "Absolutely. Every order arrives in a gift-ready box. Add a note at checkout and we'll include a handwritten card." },
    { question: "How long does shipping take?", answer: "Orders ship within 1–2 business days. Most customers in the DMV receive their order within 3–5 days." },
    { question: "What is your return policy?", answer: "We accept returns within 14 days of delivery for unworn items in original packaging. Contact us to start a return." },
  ],
  social: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
  },
}
