import type { SiteConfig } from "../types"

export const config: SiteConfig = {
  business: {
    name: "Mark Davis Real Estate",
    tagline: "Keller Williams Northern Virginia | DC Metro Area",
    phone: "+1 (703) 555-0821",
    email: "mark@markdavisrealestate.com",
    address: "1760 Reston Pkwy #200",
    city: "Reston",
    state: "VA",
    logo: "https://cdn.zikwala.com/demo/realestate/logo.png",
    niche: "realestate",
  },
  theme: {
    primary: "#1A3A5C",
    secondary: "#C9A84C",
    accent: "#EEF4FF",
    surface: "#F7F9FC",
    onPrimary: "#FFFFFF",
    font: "Montserrat",
    roundedLevel: "lg",
    darkMode: false,
  },
  tier: "standard",
  isDemo: true,
  seo: {
    title: "Mark Davis Real Estate | Keller Williams Northern Virginia",
    description:
      "Top-rated real estate agent serving Northern Virginia and the DC Metro area. Expert guidance for buyers and sellers in Reston, Tysons, Fairfax, and beyond.",
    keywords: [
      "real estate agent Northern Virginia",
      "realtor Reston VA",
      "Fairfax County real estate",
      "buy home Northern Virginia",
      "sell home DC Metro",
      "Keller Williams Virginia",
      "homes for sale Reston VA",
      "DC Metro real estate agent",
    ],
    ogImage: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
  },
  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "Properties", href: "/properties" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    ctaLabel: "Free Consultation",
    ctaHref: "/contact",
  },
  hero: {
    heading: "Your Dream Home in Northern Virginia Starts Here",
    variant: "magazine",
    subheading:
      "Trusted real estate expert serving Reston, Fairfax, Tysons, and the greater DC Metro area. Let's find your perfect home.",
    cta: { label: "Free Consultation", href: "/contact" },
    secondaryCta: { label: "View Properties", href: "/properties" },
    image: "https://cdn.zikwala.com/demo/realestate/property2.jpg",
    badge: "🏆 Top Producing Agent",
    trustPoints: ["Licensed in VA, MD & DC", "500+ Homes Sold", "Keller Williams Top Producer"],
    socialProof: { count: "500+", label: "families helped across Northern Virginia" },
  },
  services: {
    title: "Real Estate Services",
    subtitle: "Expert guidance across Northern Virginia and the DC Metro",
    items: [
      {
        name: "Home Buying",
        description:
          "From pre-approval to closing, I guide first-time and experienced buyers through every step of the Northern Virginia market.",
        icon: "Home",
      },
      {
        name: "Home Selling",
        description:
          "Strategic pricing, professional photography, and aggressive marketing to sell your home fast and at top dollar.",
        icon: "TrendingUp",
      },
      {
        name: "Investment Properties",
        description:
          "Find income-producing properties in Reston, Fairfax, Arlington, and the broader DC Metro market.",
        icon: "Building2",
      },
      {
        name: "Relocation Services",
        description:
          "Moving to Northern Virginia or the DC area? I make your transition smooth with deep local neighborhood knowledge.",
        icon: "MapPin",
      },
    ],
  },
  properties: {
    title: "Available Properties",
    subtitle: "Homes for sale and rent across Northern Virginia and DC Metro",
    items: [
      {
        id: "prop-1",
        title: "Modern Condo at Sunrise Valley",
        image: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
        address: "11760 Sunrise Valley Dr #401",
        city: "Reston, VA",
        price: 625000,
        status: "For Sale",
        type: "Condo",
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1180,
        badge: "New Listing",
      },
      {
        id: "prop-2",
        title: "Spacious Family Home in Herndon",
        image: "https://cdn.zikwala.com/demo/realestate/property2.jpg",
        address: "2480 Fox Mill Rd",
        city: "Herndon, VA",
        price: 890000,
        status: "For Sale",
        type: "House",
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2800,
      },
      {
        id: "prop-3",
        title: "Charming 4-Bed in Falls Church",
        image: "https://cdn.zikwala.com/demo/realestate/property3.jpg",
        address: "8120 Gatehouse Rd",
        city: "Falls Church, VA",
        price: 750000,
        status: "For Sale",
        type: "House",
        bedrooms: 4,
        bathrooms: 2,
        sqft: 2200,
        badge: "Open House",
      },
      {
        id: "prop-4",
        title: "Urban 1-Bed in Arlington",
        image: "https://cdn.zikwala.com/demo/realestate/property4.jpg",
        address: "3320 Wilson Blvd #506",
        city: "Arlington, VA",
        price: 3200,
        status: "For Rent",
        type: "Apartment",
        bedrooms: 1,
        bathrooms: 1,
        sqft: 820,
      },
      {
        id: "prop-5",
        title: "Move-In Ready Home in Lorton",
        image: "https://cdn.zikwala.com/demo/realestate/property5.jpg",
        address: "9450 Lorton Market St",
        city: "Lorton, VA",
        price: 568000,
        status: "For Sale",
        type: "House",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1750,
        badge: "Price Reduced",
      },
      {
        id: "prop-6",
        title: "Grand 5-Bed in Old Town Alexandria",
        image: "https://cdn.zikwala.com/demo/realestate/property6.jpg",
        address: "4220 King St",
        city: "Alexandria, VA",
        price: 920000,
        status: "Under Contract",
        type: "House",
        bedrooms: 5,
        bathrooms: 3,
        sqft: 3200,
      },
    ],
  },
  testimonials: {
    title: "Client Success Stories",
    subtitle: "Trusted by buyers and sellers across Northern Virginia",
    items: [
      {
        name: "Jennifer & Tom W.",
        role: "Home Buyers, Reston VA",
        text: "Mark made our first home purchase stress-free. He was patient, always available, and negotiated a great deal for us. We couldn't be happier with our new home in Reston.",
        rating: 5,
      },
      {
        name: "David L.",
        role: "Home Seller, Fairfax VA",
        text: "Mark sold our home in 6 days at $40k over asking price. His marketing strategy was spot on and his communication throughout was excellent. Highly recommend!",
        rating: 5,
      },
      {
        name: "Sarah & Michael K.",
        role: "Relocating Buyers, Arlington VA",
        text: "We moved from Chicago to DC Metro and Mark made it seamless. He knew every neighborhood, school district, and commute option. Found us the perfect home in Arlington.",
        rating: 5,
      },
    ],
  },
  stats: {
    items: [
      { label: "Homes Sold", value: "500+" },
      { label: "Google Rating", value: "⭐ 5.0" },
      { label: "Avg Days on Market", value: "8" },
      { label: "Award", value: "🏆 Top Producer" },
    ],
  },
  about: {
    title: "About Mark Davis",
    sections: [
      {
        heading: "Meet Mark Davis",
        body: "Mark Davis is a Keller Williams top-producing agent serving Northern Virginia and the DC Metro area. With over 12 years of experience and 500+ successful transactions, Mark brings deep market knowledge, strong negotiation skills, and genuine care to every client relationship — whether you're buying your first home or selling your forever home.",
        image: "https://cdn.zikwala.com/demo/realestate/property1.jpg",
        highlights: [
          { label: "Licensed in", value: "VA, MD & DC" },
          { label: "Brokerage", value: "KW Northern Virginia" },
          { label: "Experience", value: "12+ years" },
          { label: "Homes Sold", value: "500+" },
        ],
      },
      {
        heading: "My Commitment to You",
        body: "Real estate in Northern Virginia moves fast. I stay ahead of market trends, leverage professional marketing, and negotiate hard on your behalf. From Reston to Alexandria, from Arlington to Fairfax — I know this market inside and out. My goal is simple: get you the best outcome possible.",
        image: "https://cdn.zikwala.com/demo/realestate/property3.jpg",
      },
    ],
  },
  contact: {
    title: "Let's Talk Real Estate",
    subtitle: "Schedule your free consultation — Northern Virginia & DC Metro.",
    mapEmbed: "https://maps.google.com/maps?q=1760+Reston+Pkwy,+Reston,+VA&output=embed",
    formEndpoint: "mailto:mark@markdavisrealestate.com",
  },
  stickyContact: "both",
  googleReviewUrl: "https://g.page/r/mark-davis-real-estate/review",
  social: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
  },
}
